name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [open, reopened, synchronize, review_requested, ready_for_review]
  schedule:
    - cron: "0 4 * * *"

jobs:
  tests-cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip3 install .[dev]
    - name: Run Tests
      run: pytest -v tests/
