name: Docs Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  docs-test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn

      - name: Install docusaurus dependencies
        run: yarn install --frozen-lockfile
      - name: Install adk dependencies
        run: pip3 install -e .[dev]
      - name: Create Markdown
        run: pydoc-markdown
      - name: Test build website
        run: yarn build
